(ns music-as-data.signalsnotes
  (:use [music-as-data.signals]
        [music-as-data.globals])
  (:import [music_as_data.elements Melement]))

(defn create-notes []
  ;; FIXME - macro here!
  (defnote A0 @*sine*)
  (defnote A1 @*sine*)
  (defnote A2 @*sine*)
  (defnote A3 @*sine*)
  (defnote A4 @*sine*)
  (defnote A5 @*sine*)
  (defnote A6 @*sine*)
  (defnote A7 @*sine*)
  
  (defnote B0 @*sine*)
  (defnote B1 @*sine*)
  (defnote B2 @*sine*)
  (defnote B3 @*sine*)
  (defnote B4 @*sine*)
  (defnote B5 @*sine*)
  (defnote B6 @*sine*)
  (defnote B7 @*sine*)
  
  (defnote C0 @*sine*)
  (defnote C1 @*sine*)
  (defnote C2 @*sine*)
  (defnote C3 @*sine*)
  (defnote C4 @*sine*)
  (defnote C5 @*sine*)
  (defnote C6 @*sine*)
  (defnote C7 @*sine*)
  
  (defnote D0 @*sine*)
  (defnote D1 @*sine*)
  (defnote D2 @*sine*)
  (defnote D3 @*sine*)
  (defnote D4 @*sine*)
  (defnote D5 @*sine*)
  (defnote D6 @*sine*)
  (defnote D7 @*sine*)
  
  (defnote D#0 @*sine*)
  (defnote D#1 @*sine*)
  (defnote D#2 @*sine*)
  (defnote D#3 @*sine*)
  (defnote D#4 @*sine*)
  (defnote D#5 @*sine*)
  (defnote D#6 @*sine*)
  (defnote D#7 @*sine*)
  
  (defnote E0 @*sine*)
  (defnote E1 @*sine*)
  (defnote E2 @*sine*)
  (defnote E3 @*sine*)
  (defnote E4 @*sine*)
  (defnote E5 @*sine*)
  (defnote E6 @*sine*)
  (defnote E7 @*sine*)
  
  (defnote F0 @*sine*)
  (defnote F1 @*sine*)
  (defnote F2 @*sine*)
  (defnote F3 @*sine*)
  (defnote F4 @*sine*)
  (defnote F5 @*sine*)
  (defnote F6 @*sine*)
  (defnote F7 @*sine*)
  
  (defnote G0 @*sine*)
  (defnote G1 @*sine*)
  (defnote G2 @*sine*)
  (defnote G3 @*sine*)
  (defnote G4 @*sine*)
  (defnote G5 @*sine*)
  (defnote G6 @*sine*)
  (defnote G7 @*sine*)
  
  (defnote G#0 @*sine*)
  (defnote G#1 @*sine*)
  (defnote G#2 @*sine*)
  (defnote G#3 @*sine*)
  (defnote G#4 @*sine*)
  (defnote G#5 @*sine*)
  (defnote G#6 @*sine*)
  (defnote G#7 @*sine*))